"""add database query indexes

Revision ID: 664466c511e2
Revises: 54c2f9f63027
Create Date: 2026-08-25 19:44:01.812556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664466c511e2'
down_revision: Union[str, Sequence[str], None] = '54c2f9f63027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_complaint_status_history_complaint_id', 'complaint_status_history', ['complaint_id'], unique=False)
    op.create_index('ix_complaint_suspects_complaint_id', 'complaint_suspects', ['complaint_id'], unique=False)
    op.create_index('ix_complaints_category_id', 'complaints', ['category_id'], unique=False)
    op.create_index('ix_complaints_created_at', 'complaints', ['created_at'], unique=False)
    op.create_index('ix_complaints_status', 'complaints', ['status'], unique=False)
    op.create_index('ix_complaints_user_id', 'complaints', ['user_id'], unique=False)
    op.create_index('ix_cyber_warrior_profiles_verification_status', 'cyber_warrior_profiles', ['verification_status'], unique=False)
    op.create_index('ix_evidence_complaint_id', 'evidence', ['complaint_id'], unique=False)
    op.create_index('ix_evidence_suspect_report_id', 'evidence', ['suspect_report_id'], unique=False)
    op.create_index('ix_evidence_warrior_report_id', 'evidence', ['warrior_report_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_reported_suspects_identifier_type', 'reported_suspects', ['identifier_type'], unique=False)
    op.create_index('ix_reported_suspects_identifier_value', 'reported_suspects', ['identifier_value'], unique=False)
    op.create_index('ix_reported_suspects_status', 'reported_suspects', ['status'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_warrior_applications_status', 'warrior_applications', ['status'], unique=False)
    op.create_index('ix_warrior_applications_warrior_id', 'warrior_applications', ['warrior_id'], unique=False)
    op.create_index('ix_warrior_reports_status', 'warrior_reports', ['status'], unique=False)
    op.create_index('ix_warrior_reports_warrior_id', 'warrior_reports', ['warrior_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warrior_reports_warrior_id', table_name='warrior_reports')
    op.drop_index('ix_warrior_reports_status', table_name='warrior_reports')
    op.drop_index('ix_warrior_applications_warrior_id', table_name='warrior_applications')
    op.drop_index('ix_warrior_applications_status', table_name='warrior_applications')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_reported_suspects_status', table_name='reported_suspects')
    op.drop_index('ix_reported_suspects_identifier_value', table_name='reported_suspects')
    op.drop_index('ix_reported_suspects_identifier_type', table_name='reported_suspects')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_evidence_warrior_report_id', table_name='evidence')
    op.drop_index('ix_evidence_suspect_report_id', table_name='evidence')
    op.drop_index('ix_evidence_complaint_id', table_name='evidence')
    op.drop_index('ix_cyber_warrior_profiles_verification_status', table_name='cyber_warrior_profiles')
    op.drop_index('ix_complaints_user_id', table_name='complaints')
    op.drop_index('ix_complaints_status', table_name='complaints')
    op.drop_index('ix_complaints_created_at', table_name='complaints')
    op.drop_index('ix_complaints_category_id', table_name='complaints')
    op.drop_index('ix_complaint_suspects_complaint_id', table_name='complaint_suspects')
    op.drop_index('ix_complaint_status_history_complaint_id', table_name='complaint_status_history')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    # ### end Alembic commands ###
